### ISSUE TITLE
Unnecessary re-evaluation of closure

### ISSUE THREAD

**Issue by juan43ramirez** [manuel-delverme/constrained_optimization#4]
https://github.com/manuel-delverme/constrained_optimization/blob/6469787ea46ec45b313e45c79213673eaed995ea/src/torch_constrained/constrained_optimizer.py#L63-L65

The closure, as well as the Lagrangian, should only be evaluated if self.alternating is True. 
This slightly slows down execution.

**Comment by manuel-delverme** [comment]
Thank you
