### ISSUE TITLE
Code repetition, weighted_constraint method

### ISSUE THREAD

**Issue by juan43ramirez** [manuel-delverme/constrained_optimization#6]
https://github.com/manuel-delverme/constrained_optimization/blob/6469787ea46ec45b313e45c79213673eaed995ea/src/torch_constrained/constrained_optimizer.py#L80-L100
Lines 84 to 90 are identical to lines 93-99. Consider reformulating and calling the function once for equality multipliers and once for inequality multipliers.

**Comment by manuel-delverme** [comment]
I agree, right now the function itself is pretty small (fits the monitor) so i'm keeping it as it is, but it will be refactored as soon as it gets any bigger as you suggested
